### ISSUE TITLE
add playWithinDistance 3d audio

### ISSUE THREAD

**Issue by Slluxx** [plunkettscott/interact-sound#11]
https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Web_audio_spatialization_basics

**Comment by plunkettscott** [comment]
It's been a plan of mine, just no time to do it. There's a whole new version of this written in TypeScript that I have not gotten the time to finish. It does have the goal of spatial audio.

**Comment by Slluxx** [comment]
wow, i was already about to do it myself but thats really nice to hear.
how is it implemented? i came up with calculating the degree of the sound by triangluating the local position and the source position with the heading of the listener. though i didnt really think about that i need to calculate the actual camera position, not the peds heading.

based on that degree i could pan the sound to the left or right ear which was an ok simulation but unusable as i calculated the wrong things (did it just yesterday).

**Comment by plunkettscott** [comment]
Correct, it uses the Howler spatial audio library which handles panning and fading just by providing it the necessary headings, direction, and sound source coordinates. I'll close the other. I'd be happy to accept some help on this if you're interested in working on it.

**Comment by Slluxx** [comment]
due to my limited time because of other projects and work i am unable to really help with this. But i'd really like to use your resource as dependency for mine and get the best out of both.

i know its unfair to ask for an ETA but do you have some time to work on it in general or is it "on ice" ?

**Comment by plunkettscott** [comment]
Currently on hold for the moment. I'd like to pick it up again in the near future once I get some of my other income-providing projects released.

**Comment by CarlosVergikosk** [comment]
please, it would be awesome man! keep up !

**Comment by plunkettscott** [comment]
Just an update here, [SoundFX](https://github.com/plunkettscott/soundfx), the successor to Interact Sound is in the works. This release will include spatial audio to blend in better with the 3D world and will come with some much-needed API improvements.
