### ISSUE TITLE
Documentation is broken/missing

### ISSUE THREAD

**Issue by cbzink** [plunkettscott/interact-sound#13]
The documentation linked to in the repo - https://plunkettscott.github.io/interact-sound/start/ - seems to be broken for me. The only page displayed is the "Getting Started" page and the first sentence is cut off with nothing else following;

> Interact Sound is easy to install and use. To install it, simply fetch the latest release from

It appears the documentation linked in the original CitizenFX Forums - https://plunkettscott.gitbooks.io/scott-s-script-documentation/content/scripts/interactsound.html - is still working.

**Comment by plunkettscott** [comment]
Yeah, sorry. The first link is actually the start of the documentation for the next version which is being worked on behind the scenes. The second link is the correct link for the current version which is listed on the CitizenFX forums.

**Comment by plunkettscott** [comment]
I updated the site link to be the current version's documentation. I'll close this issue out for now.
