### ISSUE TITLE
breaks default fivem scoreboard

### ISSUE THREAD

**Issue by storm37000** [plunkettscott/interact-sound#15]
prevents default fivem scoreboard from appearing at all when this resource is enabled.

**Comment by plunkettscott** [comment]
Are you sure there isn't something else causing the UI to break? Lots of servers use this resource and this is the first I've heard of this issue.

**Comment by storm37000** [comment]
its only this one as far as i know.  I got this in conjunction with the tornado mod to allow custom sounds.

**Comment by plunkettscott** [comment]
Not sure what this is and there's not enough information here to really solve it. In addition, this resource will soon be deprecated in favor of the next iteration, [SoundFX](https://github.com/plunkettscott/soundfx).
