### ISSUE TITLE
load issue

### ISSUE THREAD

**Issue by ApexRP** [plunkettscott/interact-sound#2]
keep getting cant load resource interact-sound

**Comment by plunkettscott** [comment]
Is this with v0.2.1? Do you have a folder called "interact-sound" in your resources folder?

**Comment by ApexRP** [comment]
its the latest

**Comment by MattyShiba** [comment]
Same here,.

**Comment by plunkettscott** [comment]
@ApexRP @MattyShiba can one or both of you send me a screenshot of your resources folder and inside of the interact sound folder? You can upload it here and I'll take a look.

**Comment by plunkettscott** [comment]
Can you also send me how you are starting the resource in the `server.cfg` file?

**Comment by ApexRP** [comment]
yea sure can do 
https://gyazo.com/4c311ce49e851673eea6ac8bd6f2f6df  https://gyazo.com/4cdeab9f965dec5751930590950e39ea   
https://gyazo.com/37e25dccd96c07f4b61938d14aa9b1d6

**Comment by oaaron99** [comment]
I am also having this issue

**Comment by plunkettscott** [comment]
@ApexRP @MattyShiba 

Can you guys try now with v0.3?

**Comment by reinderhe** [comment]
Same issue here, ill try with the 3.0 version now!

**Comment by plunkettscott** [comment]
@ApexRP @MattyShiba @reinderhe 

This should be resolved with v0.4. Can you confirm?

**Comment by ApexRP** [comment]
@plunkettscott can confirm it does work didnt get any error message thanks for the update :)

**Comment by plunkettscott** [comment]
Great news! I'll get this issue closed. Thanks for letting me know it worked! Let me know if you encounter any other issues. Will be working on getting v1 in alpha very soon, it'll have all kinds of new features!
