### ISSUE TITLE
No sound whatsoever after the OneSync Update. 

### ISSUE THREAD

**Issue by imbader** [plunkettscott/interact-sound#23]

**Comment by plunkettscott** [comment]
Hi @imbader! What version were you running prior to installing the OneSync update?

**Comment by am3nd01m** [comment]
I'm having the same issue...

**Comment by plunkettscott** [comment]
@am3nd01m what version were you running prior to the OneSync update? Are there any errors in the server console or the F8 developer tools console?

**Comment by am3nd01m** [comment]
I'm not sure how to check the version, but there are no errors in the console.

**Comment by imbader** [comment]
Oh , forgot to close this issue. 

I have fixed it by 
Clearing Cache
Update latest server-data artfic

**Comment by am3nd01m** [comment]
I did this and still no sound

**Comment by imbader** [comment]
> I did this and still no sound

are u sure u triggering the sound right? show me how u're triggering it

**Comment by am3nd01m** [comment]
All fixed now, there was a " , " missing in the fxmanifest.
