### ISSUE TITLE
MF Trackable issues / adding new sounds issue

### ISSUE THREAD

**Issue by R1M0INC** [plunkettscott/interact-sound#24]
I struggle adding a new sound this is my fxmanifest

```lua
files {
    'client/html/index.html',
    -- Begin Sound Files Here...
    -- client/html/sounds/ ... .ogg
    'client/html/sounds/demo.ogg'
    'client/html/sounds/alert.ogg'
},
```

**Comment by plunkettscott** [comment]
Hi @R1M0INC,

This should work, but you'll need to call the events to play these sounds. I'll need more information on the problems your facing to be able to provide any guidance. I'd recommend taking a look at the [docs](https://plunkettscott.gitbooks.io/scott-s-script-documentation/content/scripts/interactsound.html). Are you able to get the `demo` sound to play properly?

**Comment by plunkettscott** [comment]
I just re-read this. I believe you're missing a `,` in that list. Try this:

```lua
files {
    'client/html/index.html',
    'client/html/sounds/demo.ogg',
    'client/html/sounds/alert.ogg'
}
```

**Comment by plunkettscott** [comment]
Closing since I haven't heard anything from you.
