### ISSUE TITLE
Seatbelt sound not working

### ISSUE THREAD

**Issue by OfficialBart** [plunkettscott/interact-sound#3]
in resource: SeatbeltIndicator i have put this:
```TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 0.5, 'demo', 1.0)```
for testing the demo sound and that is not working..

resource name voor the interact sound is: interact-sound

can you help me?

**Comment by plunkettscott** [comment]
@OfficialBart,

Can you try it now with v0.3?

**Comment by OfficialBart** [comment]
yeah it works!
ty :)

**Comment by OfficialBart** [comment]
only the ``InteractSound_SV:PlayWithinDistance`` is not working now,
```TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 0.5, 'demo', 1.0)```

**Comment by plunkettscott** [comment]
@OfficialBart, this is resolved with 0.4.1.
