### ISSUE TITLE
Syntax Error?

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [plunkettscott/interact-sound#34]
Disregard

**Comment by ViolentMinds** [comment]
The entire script (its part of Badger Bank Robbery I'm trying to simply play an Alarm sound to all clients nearby the source player, OneSync is enabled.

`-------------------------
--- BadgerBankRobbery ---
-------------------------

robberyActive = false
RegisterNetEvent('BadgerBankRobbery:IsActive:Return')
AddEventHandler('BadgerBankRobbery:IsActive:Return', function(bool)
	robberyActive = bool
end)

Citizen.CreateThread(function()
	while true do
		Citizen.Wait(0)

		if not robberyActive then
			if (config.enableBanks == true) then
				for _, bankcoords in pairs(config.bankcoords) do
				DrawMarker(27, bankcoords.x, bankcoords.y, bankcoords.z, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.0, 4.0, .2, 255, 0, 0, 255, false, true, 2, false, nil, nil, false)
				end
			end

			if (config.enableAmmunations == true) then
				for _, ammunationcoords in pairs(config.ammunationcoords) do
				DrawMarker(27, ammunationcoords.x, ammunationcoords.y, ammunationcoords.z, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.0, 3.0, .2, 255, 0, 0, 255, false, true, 2, false, nil, nil, false)
				end
			end

			if (config.enable247 == true) then
				for _, shopcoords in pairs(config.shopcoords) do
				DrawMarker(27, shopcoords.x, shopcoords.y, shopcoords.z, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.0, 3.0, .2, 255, 0, 0, 255, false, true, 2, false, nil, nil, false)
				end
			end

			if (config.enableGasStations == true) then
				for _, ltdcoords in pairs(config.ltdcoords) do
				DrawMarker(27, ltdcoords.x, ltdcoords.y, ltdcoords.z, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.0, 3.0, .2, 255, 0, 0, 255, false, true, 2, false, nil, nil, false)
				end
			end

			if (config.enableLiquor == true) then
				for _, liquorcoords in pairs(config.liquorcoords) do
				DrawMarker(27, liquorcoords.x, liquorcoords.y, liquorcoords.z, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.0, 3.0, .2, 255, 0, 0, 255, false, true, 2, false, nil, nil, false)
				end
			end

			-- Bank Code
			local coords = GetEntityCoords(GetPlayerPed(-1))
			for _, bankcoords in pairs(config.bankcoords) do
			if (config.enableBanks == true) then
				if GetDistanceBetweenCoords(coords.x, coords.y, coords.z, bankcoords.x, bankcoords.y, bankcoords.z, true) < 0.8 then
		--			DisplayNotification('~r~Press the ~w~E ~r~key to rob the bank')
					if IsControlJustReleased(0, 38) then -- E key
						TriggerServerEvent('BadgerBankRobbery:SetActive', true)
						TriggerServerEvent('PrintBR:PrintMessage', bankcoords.alarm)
						RegisterNetEvent('InteractSound_SV:PlayWithinDistance')
AddEventHandler('InteractSound_SV:PlayWithinDistance', function(100, 'alarm.ogg', 1.0)
  if GetConvar("onesync_enableInfinity", "false") == "true" then
    TriggerClientEvent('InteractSound_CL:PlayWithinDistanceOS', -1, GetEntityCoords(GetPlayerPed(source)), 100, 'alarm.ogg', 1.0)
  else
    TriggerClientEvent('InteractSound_CL:PlayWithinDistance', -1, source, 100, 'alarm.ogg', 1.0)
  end
end)

RegisterNetEvent('InteractSound_SV:PlayWithinDistance')
AddEventHandler('InteractSound_SV:PlayWithinDistance', function(100, 'alarm.ogg', 1.0)
    local src = source
    local DistanceLimit = 300
    if maxDistance < DistanceLimit then
	TriggerClientEvent('InteractSound_CL:PlayWithinDistance', -1, GetEntityCoords(GetPlayerPed(src)), 100, 'alarm.ogg', 1.0)
    else
        print(('[interact-sound] [^3WARNING^7] %s attempted to trigger InteractSound_SV:PlayWithinDistance over the distance limit ' .. DistanceLimit):format(GetPlayerName(src)))
    end
end)
						if (config.displayBlips == true) then
							bankcoords.blip = AddBlipForCoord(bankcoords.x, bankcoords.y, bankcoords.z)
							SetBlipSprite(bankcoords.blip, 161)
							SetBlipFlashTimer(bankcoords.blip, 3000 * config.timeToRob)
							SetBlipAsShortRange(bankcoords.blip, false)
							BeginTextCommandSetBlipName("STRING")
							AddTextComponentString(bankcoords.name)
							EndTextCommandSetBlipName(bankcoords.blip)
						end
						TriggerEvent("mythic_progbar:client:progress", {
							name = "RobbingTheBank",
							duration = (1000 * config.timeToRob), -- 1000ms * x seconds
							label = config.robbingStr,
							useWhileDead = false,
							canCancel = true,
							controlDisables = {
								disableMovement = false,
								disableCarMovement = true,
								disableMouse = false,
								disableCombat = true,
							},
							animation = {
								animDict = "anim@amb@clubhouse@tutorial@bkr_tut_ig3@",
								anim = "machinic_loop_mechandplayer",
								flags = 49,
							},
							prop = {
								model = "prop_int_crowbar",
							}
						}, function(status)
							if not status and not IsEntityDead(GetPlayerPed(-1)) then
								DisplayNotification('~g~Success: You have robbed the bank successfully!')
								TriggerServerEvent('PrintBR:PrintMessage', config.robberySuccess)
							else
								DisplayNotification('~r~Failed: Your bank robbery has failed.')
								TriggerServerEvent('PrintBR:PrintMessage', config.robberyFailed)
							end
						end)
						Wait(3000 * config.timeToRob)
						RemoveBlip(bankcoords.blip)
					end
				end
			end
			end

			-- Ammunation Code
			for _, ammunationcoords in pairs(config.ammunationcoords) do
			if (config.enableAmmunations == true) then
				if GetDistanceBetweenCoords(coords.x, coords.y, coords.z, ammunationcoords.x, ammunationcoords.y, ammunationcoords.z) < 0.8 then
			--		DisplayNotification('~r~Press the ~w~E ~r~key to rob the Ammunation')
					if IsControlJustReleased(0, 38) then -- E
						TriggerServerEvent('PrintBR:PrintMessage', ammunationcoords.alarm)
						TriggerServerEvent('BadgerBankRobbery:SetActive', true)
						RegisterNetEvent('InteractSound_SV:PlayWithinDistance')
AddEventHandler('InteractSound_SV:PlayWithinDistance', function(100, 'alarm.ogg', 1.0)
  if GetConvar("onesync_enableInfinity", "false") == "true" then
    TriggerClientEvent('InteractSound_CL:PlayWithinDistanceOS', -1, GetEntityCoords(GetPlayerPed(source)), 100, 'alarm.ogg', 1.0)
  else
    TriggerClientEvent('InteractSound_CL:PlayWithinDistance', -1, source, 100, 'alarm.ogg', 1.0)
  end
end)

RegisterNetEvent('InteractSound_SV:PlayWithinDistance')
AddEventHandler('InteractSound_SV:PlayWithinDistance', function(100, 'alarm.ogg', 1.0)
    local src = source
    local DistanceLimit = 300
    if maxDistance < DistanceLimit then
	TriggerClientEvent('InteractSound_CL:PlayWithinDistance', -1, GetEntityCoords(GetPlayerPed(src)), 100, 'alarm.ogg', 1.0)
    else
        print(('[interact-sound] [^3WARNING^7] %s attempted to trigger InteractSound_SV:PlayWithinDistance over the distance limit ' .. DistanceLimit):format(GetPlayerName(src)))
    end
end)
						if (config.displayBlips == true) then
							ammunationcoords.blip = AddBlipForCoord(ammunationcoords.x, ammunationcoords.y, ammunationcoords.z)
							SetBlipSprite(ammunationcoords.blip, 161)
							SetBlipFlashTimer(ammunationcoords.blip, 3000 * config.timeToRob)
							SetBlipAsShortRange(ammunationcoords.blip, true)
							BeginTextCommandSetBlipName("STRING")
							AddTextComponentString(ammunationcoords.name)
							EndTextCommandSetBlipName(ammunationcoords.blip)
						end
						TriggerEvent("mythic_progbar:client:progress", {
							name = "RobbingTheBank",
							duration = (1000 * config.timeToRob), -- 1000ms * x seconds
							label = config.robbingStr,
							useWhileDead = false,
							canCancel = true,
							controlDisables = {
								disableMovement = false,
								disableCarMovement = true,
								disableMouse = false,
								disableCombat = true,
							},
							animation = {
								animDict = "anim@amb@clubhouse@tutorial@bkr_tut_ig3@",
								anim = "machinic_loop_mechandplayer",
								flags = 49,
							},
							prop = {
								model = "crowbar",
							}
						}, function(status)
							if not status and not IsEntityDead(GetPlayerPed(-1)) then
								DisplayNotification('~g~Success: You have robbed the Ammunation successfully!')
								TriggerServerEvent('PrintBR:PrintMessage', config.robberySuccess)
							else
								DisplayNotification('~r~Failed: Your Ammunation robbery has failed.')
								TriggerServerEvent('PrintBR:PrintMessage', config.robberyFailed)
							end
						end)
						Wait(1000 * config.timeToRob)
						RemoveBlip(ammunationcoords.blip)
					end
				end
			end
			end

			-- 24/7 Code
			for _, shopcoords in pairs(config.shopcoords) do
			if (config.enable247 == true) then
				if GetDistanceBetweenCoords(coords.x, coords.y, coords.z, shopcoords.x, shopcoords.y, shopcoords.z) < 0.8 then
			--		DisplayNotification('~r~Press the ~w~E ~r~key to rob the store')
					if IsControlJustReleased(0, 38) then -- E
						TriggerServerEvent('PrintBR:PrintMessage', shopcoords.alarm)
						TriggerServerEvent('BadgerBankRobbery:SetActive', true)
						RegisterNetEvent('InteractSound_SV:PlayWithinDistance')
AddEventHandler('InteractSound_SV:PlayWithinDistance', function(100, 'alarm.ogg', 1.0)
  if GetConvar("onesync_enableInfinity", "false") == "true" then
    TriggerClientEvent('InteractSound_CL:PlayWithinDistanceOS', -1, GetEntityCoords(GetPlayerPed(source)), 100, 'alarm.ogg', 1.0)
  else
    TriggerClientEvent('InteractSound_CL:PlayWithinDistance', -1, source, 100, 'alarm.ogg', 1.0)
  end
end)

RegisterNetEvent('InteractSound_SV:PlayWithinDistance')
AddEventHandler('InteractSound_SV:PlayWithinDistance', function(100, 'alarm.ogg', 1.0)
    local src = source
    local DistanceLimit = 300
    if maxDistance < DistanceLimit then
	TriggerClientEvent('InteractSound_CL:PlayWithinDistance', -1, GetEntityCoords(GetPlayerPed(src)), 100, 'alarm.ogg', 1.0)
    else
        print(('[interact-sound] [^3WARNING^7] %s attempted to trigger InteractSound_SV:PlayWithinDistance over the distance limit ' .. DistanceLimit):format(GetPlayerName(src)))
    end
end)
						if (config.displayBlips == true) then
							shopcoords.blip = AddBlipForCoord(shopcoords.x, shopcoords.y, shopcoords.z)
							SetBlipSprite(shopcoords.blip, 161)
							SetBlipFlashTimer(shopcoords.blip, 3000 * config.timeToRob)
							SetBlipAsShortRange(shopcoords.blip, true)
							BeginTextCommandSetBlipName("STRING")
							AddTextComponentString(shopcoords.name)
							EndTextCommandSetBlipName(shopcoords.blip)
						end
						TriggerEvent("mythic_progbar:client:progress", {
							name = "RobbingTheBank",
							duration = (1000 * config.timeToRob), -- 1000ms * x seconds
							label = config.robbingStr,
							useWhileDead = false,
							canCancel = true,
							controlDisables = {
								disableMovement = false,
								disableCarMovement = true,
								disableMouse = false,
								disableCombat = true,
							},
							animation = {
								animDict = "anim@amb@clubhouse@tutorial@bkr_tut_ig3@",
								anim = "machinic_loop_mechandplayer",
								flags = 49,
							},
							prop = {
								model = "crowbar",
							}
						}, function(status)
							if not status and not IsEntityDead(GetPlayerPed(-1)) then
								DisplayNotification('~g~Success: You have robbed the 24/7 successfully!')
								TriggerServerEvent('PrintBR:PrintMessage', config.robberySuccess)
							else
								DisplayNotification('~r~Failed: Your 24/7 robbery has failed.')
								TriggerServerEvent('PrintBR:PrintMessage', config.robberyFailed)
							end
						end)
						Wait(1000 * config.timeToRob)
						RemoveBlip(shopcoords.blip)
					end
				end
			end
			end

			-- LTD Code
			for _, ltdcoords in pairs(config.ltdcoords) do
			if (config.enableGasStations == true) then
				if GetDistanceBetweenCoords(coords.x, coords.y, coords.z, ltdcoords.x, ltdcoords.y, ltdcoords.z) < 0.8 then
				--	DisplayNotification('~r~Press the ~w~E ~r~key to rob the LTD Gas Station')
					if IsControlJustReleased(0, 38) then -- E
						TriggerServerEvent('PrintBR:PrintMessage', ltdcoords.alarm)
						TriggerServerEvent('BadgerBankRobbery:SetActive', true)
						RegisterNetEvent('InteractSound_SV:PlayWithinDistance')
AddEventHandler('InteractSound_SV:PlayWithinDistance', function(100, 'alarm.ogg', 1.0)
  if GetConvar("onesync_enableInfinity", "false") == "true" then
    TriggerClientEvent('InteractSound_CL:PlayWithinDistanceOS', -1, GetEntityCoords(GetPlayerPed(source)), 100, 'alarm.ogg', 1.0)
  else
    TriggerClientEvent('InteractSound_CL:PlayWithinDistance', -1, source, 100, 'alarm.ogg', 1.0)
  end
end)

RegisterNetEvent('InteractSound_SV:PlayWithinDistance')
AddEventHandler('InteractSound_SV:PlayWithinDistance', function(100, 'alarm.ogg', 1.0)
    local src = source
    local DistanceLimit = 300
    if maxDistance < DistanceLimit then
	TriggerClientEvent('InteractSound_CL:PlayWithinDistance', -1, GetEntityCoords(GetPlayerPed(src)), 100, 'alarm.ogg', 1.0)
    else
        print(('[interact-sound] [^3WARNING^7] %s attempted to trigger InteractSound_SV:PlayWithinDistance over the distance limit ' .. DistanceLimit):format(GetPlayerName(src)))
    end
end)
						if (config.displayBlips == true) then
							ltdcoords.blip = AddBlipForCoord(ltdcoords.x, ltdcoords.y, ltdcoords.z)
							SetBlipSprite(ltdcoords.blip, 161)
							SetBlipFlashTimer(ltdcoords.blip, 3000 * config.timeToRob)
							SetBlipAsShortRange(ltdcoords.blip, true)
							BeginTextCommandSetBlipName("STRING")
							AddTextComponentString(ltdcoords.name)
							EndTextCommandSetBlipName(ltdcoords.blip)
						end
						TriggerEvent("mythic_progbar:client:progress", {
							name = "RobbingTheBank",
							duration = (1000 * config.timeToRob), -- 1000ms * x seconds
							label = config.robbingStr,
							useWhileDead = false,
							canCancel = true,
							controlDisables = {
								disableMovement = false,
								disableCarMovement = true,
								disableMouse = false,
								disableCombat = true,
							},
							animation = {
								animDict = "anim@amb@clubhouse@tutorial@bkr_tut_ig3@",
								anim = "machinic_loop_mechandplayer",
								flags = 49,
							},
							prop = {
								model = "crowbar",
							}
						}, function(status)
							if not status and not IsEntityDead(GetPlayerPed(-1)) then
								DisplayNotification('~g~Success: You have robbed the LTD Gas Station successfully!')
								TriggerServerEvent('PrintBR:PrintMessage', config.robberySuccess)
							else
								DisplayNotification('~r~Failed: Your LTD Gas Station robbery has failed.')
								TriggerServerEvent('PrintBR:PrintMessage', config.robberyFailed)
							end
						end)
						Wait(1000 * config.timeToRob)
						RemoveBlip(ltdcoords.blip)
					end
				end
			end
			end

			-- Liquor Store Code
			for _, liquorcoords in pairs(config.liquorcoords) do
			if (config.enableLiquor == true) then
				if GetDistanceBetweenCoords(coords.x, coords.y, coords.z, liquorcoords.x, liquorcoords.y, liquorcoords.z) < 0.8 then
					--DisplayNotification('~r~Press the ~w~E ~r~key to rob the Liquor Store')
					if IsControlJustReleased(0, 38) then -- E
						TriggerServerEvent('PrintBR:PrintMessage', liquorcoords.alarm)
						TriggerServerEvent('BadgerBankRobbery:SetActive', true)
						RegisterNetEvent('InteractSound_SV:PlayWithinDistance')
AddEventHandler('InteractSound_SV:PlayWithinDistance', function(100, 'alarm.ogg', 1.0)
  if GetConvar("onesync_enableInfinity", "false") == "true" then
    TriggerClientEvent('InteractSound_CL:PlayWithinDistanceOS', -1, GetEntityCoords(GetPlayerPed(source)), 100, 'alarm.ogg', 1.0)
  else
    TriggerClientEvent('InteractSound_CL:PlayWithinDistance', -1, source, 100, 'alarm.ogg', 1.0)
  end
end)

RegisterNetEvent('InteractSound_SV:PlayWithinDistance')
AddEventHandler('InteractSound_SV:PlayWithinDistance', function(100, 'alarm.ogg', 1.0)
    local src = source
    local DistanceLimit = 300
    if maxDistance < DistanceLimit then
	TriggerClientEvent('InteractSound_CL:PlayWithinDistance', -1, GetEntityCoords(GetPlayerPed(src)), 100, 'alarm.ogg', 1.0)
    else
        print(('[interact-sound] [^3WARNING^7] %s attempted to trigger InteractSound_SV:PlayWithinDistance over the distance limit ' .. DistanceLimit):format(GetPlayerName(src)))
    end
end)
						if (config.displayBlips == true) then
						liquorcoords.blip = AddBlipForCoord(liquorcoords.x, liquorcoords.y, liquorcoords.z)
						SetBlipSprite(liquorcoords.blip, 161)
						SetBlipFlashTimer(liquorcoords.blip, 3000 * config.timeToRob)
						SetBlipAsShortRange(liquorcoords.blip, true)
						BeginTextCommandSetBlipName("STRING")
						AddTextComponentString(liquorcoords.name)
						EndTextCommandSetBlipName(liquorcoords.blip)
						TriggerEvent("mythic_progbar:client:progress", { 
							name = "RobbingTheBank",
							duration = (1000 * config.timeToRob), -- 1000ms * x seconds
							label = config.robbingStr,
							useWhileDead = false,
							canCancel = true,
							controlDisables = {
								disableMovement = false,
								disableCarMovement = true,
								disableMouse = false,
								disableCombat = true,
							},
							animation = {
								animDict = "anim@amb@clubhouse@tutorial@bkr_tut_ig3@",
								anim = "machinic_loop_mechandplayer",
								flags = 49,
							},
							prop = {
								model = "crowbar",
							}
						}, function(status)
							if not status and not IsEntityDead(GetPlayerPed(-1)) then
								DisplayNotification('~g~Success: You have robbed the Liquor Store successfully!')
								TriggerServerEvent('PrintBR:PrintMessage', config.robberySuccess)
							else
								DisplayNotification('~r~Failed: Your Liquor Store robbery has failed.')
								TriggerServerEvent('PrintBR:PrintMessage', config.robberyFailed)
							end
						end)
						Wait(1000 * config.timeToRob)
						RemoveBlip(liquorcoords.blip)
					end
				end
			end
			end
		end
	end
end)


function DisplayNotification( text )
    SetNotificationTextEntry( "STRING" )
    AddTextComponentString( text )
    DrawNotification( false, false )
end

Citizen.CreateThread(function()
	while true do
		Citizen.Wait(1000)
		TriggerServerEvent('BadgerBankRobbery:IsActive')
	end
end)`
