### ISSUE TITLE
after a certain time the sound becomes weird

### ISSUE THREAD

**Issue by OfficialBart** [plunkettscott/interact-sound#5]
When i am in my car and i hear the seatbelt alarm tone its fine, but after a certain of time the sound is going to make a weird cracking sound.

**Comment by plunkettscott** [comment]
Does it happen with any other resources/sounds aside from your seatbelt sound? This isn't the proper place for support for a specific resources use of Interact Sound, if you can provide some more information, such as the resource that is being used, I can take a look and see if it might be the cause of the resource or on our end.

**Comment by plunkettscott** [comment]
@OfficialBart 

Going to close this issue out since I haven't heard from you. Let me know if you want to continue discussion on this.
