### ISSUE TITLE
Cut sound

### ISSUE THREAD

**Issue by Drakeny** [plunkettscott/interact-sound#6]
Hi, i was doing some testing and i'm having the following problem:

i'm using
`TriggerServerEvent('InteractSound_SV:PlayWithinDistance', 20, 'demo', 1.0)`
and having it get called with a chatcommand and key press, but the sound always gets cut immediately after it starts, then i tested it inside a car and the sound played without any problems, i then called a friend to join the server to see if he would hear the cut sound too, tested it all again:

Outside of the car: Both of us got the sound cut
Inside of the car: Both of us got the sound cut
One inside and one outside of the car: I was inside and could hear the sound without any problems but my friend heard it cut...

Any ideas what could be happening?

**Comment by Drakeny** [comment]
Nevermind, found a rougue script spamming the hell out of a missing sound that was probably messing everything up. closing this.

**Comment by plunkettscott** [comment]
Thanks for the update @Drakeny!

Let me know if you notice the issue still occurring. Admittedly, I probably won't make many more fixes to the current release unless someone submits a PR. Currently working on a new version which will provide a much better experience, but will include many breaking changes.
