### ISSUE TITLE
audioPlayer.pause() issue

### ISSUE THREAD

**Issue by DJJeffP** [plunkettscott/interact-sound#7]
Hi,

When I want to play a sound nothing plays, well I think it's playing but it pauses before you can actually hear something I think.

When I remove:
               
`if (audioPlayer != null) {`
`     audioPlayer.pause();`
`}`

Then the sound plays but after a amount of use of the player with several sounds it gets crackling and after that it stops totally playing any sound.
Looks like a overstack of the sounds. 
Is there a way to improve the audioPlayer.pause() so it only pauses when the file is done playing or no sound is triggered?

Thank you in advance.

**Comment by DJJeffP** [comment]
Nevermind, I found my issue. 

For everyone who had the same issue with after a time the sound cracking up and that the resource was stopping from playing sounds, please do the following: open in you web browser http://localhost:13172 and see if you got some errors according playing sounds from interact-sound. 

If your missing a file or a another resource (like SeatbeltIndicator for example) spamming the interact-sound with play requests. Than you need to fix that first. 
The spamming/missing ogg file was causing the issue for me.

I still have this removed from the script by-the-way:

`if (audioPlayer != null) {`
`audioPlayer.pause();`
`}`

I hope this solution is helpful for a lot of people.

@plunkettscott maybe implement in your help/installation file how to bug fix this like I described above.

**Comment by plunkettscott** [comment]
@DJJeffP -

Thanks for the update. Feel free to PR the README and add a FAQ section on things you see. :)

**Comment by plunkettscott** [comment]
I would also recommend against removing that if statement, if audioPlayer is not caught when null it'll break when trying to run the `pause()` method.
