### ISSUE TITLE
Everyone can hear sound, but i want only a certain job to hear it

### ISSUE THREAD

**Issue by KingRyuShin** [plunkettscott/interact-sound#9]
I want to make it so only police hear the sound when receiving a notification.. but everyone on the server receive it even tho it's in a loop.. anyone can help ?

```
    local source = source
    local xPlayer = ESX.GetPlayerFromId(source)
    local Players = ESX.GetPlayers()

    for i = 1, #Players do
        local xPlayer = ESX.GetPlayerFromId(Players[i])

        if xPlayer["job"]["name"] == "police" then
        	TriggerClientEvent('InteractSound_CL:PlayOnOne', xPlayer.source, 'dispatch', 0.1)           
        end
    end 
```

**Comment by plunkettscott** [comment]
Were you able to figure this out yourself? I'm not familiar with ESX.

**Comment by DokaDoka** [comment]
if anyone is still wondering how to do this check out my fork: [interact sound](https://github.com/Sov-Nation/interact-sound)

**Comment by plunkettscott** [comment]
Closing as a solution was introduced in a fork. This resource will soon be deprecated in favor of the next version, [SoundFX](https://github.com/plunkettscott/soundfx).
